export let domElems = {
        logo: $('#header__logo'),
        naviScreen: $('#nav'),
        btnConfirm: $('#nav__confirm'),
        collector: $('#collector'),
        teamInput: $('#collector__input'),
        btnAdd: $('#collector__add'),
        btnGenerate: $('#collector__generate'),
        btnPDFShedule: $('#generatePDFplan'),
        btnPDFLadder: $('#generatePDFladder'),
        btnPDFLadderSection: $('#btnPDFLadderSection'),
        teamList: $('#collector__list'),
        teamOnList: $('#collector__listItem'),
        result: $('#result'),
        collectorAlertA: $('#alertOne'),
        collectorAlertB: $('#alertTwo'),
        collectorAlertC: $('#alertThree'),
        collectorAlertD: $('#alertFour'),
        resultList: $('#result_list'),
        sheduleOnScreenA: $('#result__listA'),
        sheduleOnScreenB: $('#result__listB'),
        sheduleOnScreenC: $('#result__listC'),
        sheduleOnScreenD: $('#result__listD'),
        cupCaution: $('#alertCup'),
        cupLadder: $('#result__lader'),
        ladder_round1: $('#ladder_round1'),
        ladder_round2: $('#ladder_round2'),
        ladder_round3: $('#ladder_round3'),
        ladder_round4: $('#ladder_round4'),
        ladder_round5: $('#ladder_round5'),
        ladder_round6: $('#ladder_round6'),
        line_container1: $('#line_contR1'), 
        line_container2: $('#line_contR2'), 
        line_container3: $('#line_contR3'),
        line_container4: $('#line_contR4'), 
        line_container5: $('#line_contR5'), 
        line_container6: $('#line_contR6') 
    }
 
 